version: 2.1

jobs:
  swiftlint_check:
    macos:
      xcode: 16.2.0
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install Fastlane
          command: bundle install
      - run:
          name: Install SwiftLint (Homebrew)
          command: brew install swiftlint
      - run:
          name: Run SwiftLint via Fastlane
          command: bundle exec fastlane lint_code

  build-and-test:
    macos:
      xcode: 16.2.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: brew install xcbeautify
      - run: cp ./PlayolaRadio/Config/Secrets-Example.xcconfig ./PlayolaRadio/Config/Secrets.xcconfig
      - run: cp ./PlayolaRadio/Config/Secrets-Example.xcconfig ./PlayolaRadio/Config/Secrets-Development.xcconfig
      - run: cp ./PlayolaRadio/Config/Secrets-Example.xcconfig ./PlayolaRadio/Config/Secrets-Local.xcconfig
      - run: bundle install
      - run:
          name: Configure Git for private repos
          command: git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      - run:
          name: Resolve Swift Package Dependencies
          command: xcodebuild -resolvePackageDependencies -project PlayolaRadio.xcodeproj
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: "./fastlane/test_output"
      - store_test_results:
          path: test-results

  adhoc:
    macos:
      xcode: 16.2.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    steps:
      - checkout
      - run: brew install xcbeautify
      - run: cp ./PlayolaRadio/Config/Secrets-Example.xcconfig ./PlayolaRadio/Config/Secrets.xcconfig
      - run: cp ./PlayolaRadio/Config/Secrets-Example.xcconfig ./PlayolaRadio/Config/Secrets-Development.xcconfig
      - run: cp ./PlayolaRadio/Config/Secrets-Example.xcconfig ./PlayolaRadio/Config/Secrets-Local.xcconfig
      - run: bundle install
      - run:
          name: Configure Git for private repos
          command: git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: test-results

workflows:
  lint-codebase:
    jobs:
      - swiftlint_check

  build-test-adhoc:
    jobs:
      - build-and-test
      - adhoc:
          filters:
            branches:
              only: development
          requires:
            - build-and-test
