# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(project: "PlayolaRadio.xcodeproj", scheme: "PlayolaRadio")
    upload_to_testflight
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      include_simulator_logs: false,
      parallel_testing: false,
      scheme: "PlayolaRadio",
      xcargs: "-skipMacroValidation -skipPackagePluginValidation",
      xcodebuild_formatter: "xcbeautify",
      output_directory: './fastlane/test_output/xctest')
  end

  lane :lint_code do
    swiftlint(
        mode: :lint,
        strict: true, # Fails on warnings
        config_file: ".swiftlint.yml",
        executable: "swiftlint"
    )
  end

  desc "Run swift-format lint check"
  lane :format_check do
    sh("find .. -name '*.swift' -not -path '../.build/*' -not -path '../DerivedData/*' | xargs xcrun swift-format lint --strict")
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end
end
